version: '3.9'
services:
  ambassador_backend:
    build: .
    networks:
      - ambassador
      - users
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - ambassador_db
    container_name: ambassador-backend

  ambassador_db:
    image: mysql:8
    restart: always
    container_name: ambassador-db
    networks:
      - ambassador
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql

  ambassador_redis:
    image: redis
    container_name: ambassador-redis
    networks:
      - ambassador
    ports:
      - "6379:6379"

networks:
  users:
    external:
      name: users
  ambassador:
