version: '3.9'
services:
  backend:
    build: .
    networks:
      - monolith
      - users
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db
    container_name: backend

  db:
    image: mysql:8
    restart: always
    container_name: db
    networks:
      - monolith
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

networks:
  users:
    external:
      name: users
  monolith:
