version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db
    container_name: backend-ambassador

  db:
    image: mysql:8
    restart: always
    container_name: db-ambassador
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

  redis:
    image: redis
    container_name: redis-ambassador
    ports:
      - "6379:6379"
