version: '3.9'
services:
  users_backend:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - users_db
    container_name: users-backend-ambassador

  users_db:
    image: mysql:8
    restart: always
    container_name: users-db-ambassador
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
